#!/bin/sh
# llista de nodes a controlar
LLISTA="node1 node2 node3 node4 node6 node7 node8 node9 node10 node11 node12 node13 node14 node15 node16 node17 node18 node19 node20 node21 node22"
# Fitxer de control: el creem i ens assegurem que esta buit
if [ ! /tmp/nodes.txt ]
then
        touch /tmp/nodes.txt
fi
cat /dev/null > /tmp/nodes.txt

# comprovem que podem fer ssh als nodes
for node in $LLISTA
do
        result=`ssh $node hostname 2>&1 /dev/null`
        if [ -n "$result" ]
        then
        echo "problemes a $node" >> /tmp/nodes.txt
        fi
done

# ara mirem el resultat i donem l'output en funcio dels limit
LIMIT_W=$1

result=`cat /tmp/nodes.txt`
critical=`cat /tmp/nodes.txt | wc -l`

if [ -z "$result" ]
then
echo "OK : tots els nodes accepten ssh"
fi

if [ $critical -lt $LIMIT_W ] && [ $critical -gt 0 ]
then
echo "WARNING: $result"
fi

if [ $critical -ge $LIMIT_W ]
then
echo "CRITICAL: $result"
fi



