#!/bin/bash


hostname=`hostname`
if [ $# -ne 3 ]; then
	echo "${hostname}_`basename $0` Usage $0 fileset threshold_warning threshold_critical without %"
	echo "example: $0 scratch 15 5"
	exit 1;
fi
fileset=$1


US=`df -h /gpfs/$fileset | tail -1 | awk {'print $5'} | tr '\%' ' '`


ESPAI_LLIURE=`echo "100 -$US" | bc`

WARNING=$2
CRITICAL=$3

if  [ $ESPAI_LLIURE -gt $WARNING ]
then
	echo "OK:  $ESPAI_LLIURE'%' LEFT on /gpfs/$fileset" 
fi
if [ $ESPAI_LLIURE -le $WARNING ] && [ $ESPAI_LLIURE -gt $CRITICAL ]
then
	echo "WARNING: Only $ESPAI_LLIURE'%' LEFT on /gpfs/$fileset"
fi

if [ $ESPAI_LLIURE -le $CRITICAL ]
then
	echo "CRITICAL: Only $ESPAI_LLIURE'%' LEFT on /gpfs/$fileset" 
fi

