#!/bin/sh
# llista de nodes a controlar
LLISTA="node1 node2 node3 node4 node5 node6 node7 node8 node10 node11 node12 node13 node14 node16 node17 node18 node19 node21 node22 node23 node24 node25 node26 node27 node28 node29 node30 node31 node32 node33 node34 node35 node36 node37 node38 node39 node40 node41 node42 node43 node44 node46 node47 node48 node49 node51 node52"
# Fitxer de control: el creem i ens assegurem que esta buit
if [ ! /tmp/nodes.txt ]
then
	touch /tmp/nodes.txt
fi
cat /dev/null > /tmp/nodes.txt

# comprovem que podem fer ssh als nodes
for node in $LLISTA
do
	result=`ssh $node hostname 2>&1 > /dev/null`
 	if [ -n "$result" ]
	then
	echo "problemes a $node" >> /tmp/nodes.txt
	fi
done

# ara mirem el resultat i donem l'output en funcio dels limit
LIMIT=$1

result=`cat /tmp/nodes.txt`
critical=`cat /tmp/nodes.txt | wc -l`
llistaN=`cat /tmp/nodes.txt | awk {'print $3'}`

if [ -z "$result" ]
then
echo "OK : tots els nodes accepten ssh"
fi

if [ -n "$result" ] && [ $critical -lt $LIMIT ]
then
echo "WARNING: problemes a $critical nodes"
fi

if [ $critical -ge $LIMIT ]
then
echo "CRITICAL: problemes a $critical nodes"
fi


