#!/bin/sh
#
export PATH=/usr/local/slurm/bin:$PATH

WARNING=$1
CRITICAL=$2

ALL=`squeue | wc -l`
RUNNING=`squeue -t R | wc -l`
PENDING=`echo " $ALL - $RUNNING " | bc`

if [ $PENDING -lt $WARNING ]
then
echo "OK : $PENDING jobs pending"
fi

if [ $PENDING -ge $WARNING ] && [ $PENDING -lt $CRITICAL ]
then
echo "WARNING: $PENDING jobs pending"
fi

if [ $PENDING -ge $CRITICAL ]
then
echo "CRITICAL: $PENDING jobs pending"
fi

